"use client";

export type AvatarState =
  | "idle"
  | "listening"
  | "thinking"
  | "speaking"
  | "error";

interface AvatarInputs {
  /** The microphone is actively capturing the user. */
  isListening: boolean;
  /** A reply is being generated by the backend. */
  isResponding: boolean;
  /** The assistant is currently voicing its latest reply. */
  isSpeaking?: boolean;
  /** The last interaction failed. */
  hasError?: boolean;
}

const LABELS: Record<AvatarState, string> = {
  idle: "Idle",
  listening: "Listening",
  thinking: "Thinking",
  speaking: "Speaking",
  error: "Error",
};

/**
 * Maps the live conversation/voice signals onto a single avatar state.
 * Priority (highest first): error → speaking → listening → thinking → idle.
 * Errors and active speech always win so the avatar never hides a problem
 * or talks over itself.
 */
export function useAvatar({
  isListening,
  isResponding,
  isSpeaking = false,
  hasError = false,
}: AvatarInputs) {
  const state: AvatarState = hasError
    ? "error"
    : isSpeaking
      ? "speaking"
      : isListening
        ? "listening"
        : isResponding
          ? "thinking"
          : "idle";

  return {
    state,
    label: LABELS[state],
  };
}
